const NS='http://www.w3.org/2000/svg',KEY='soccerPlannerV5',LIB='soccerPlannerLibraryV5';
const ZONE_COLS=3, ZONE_ROWS=5, FIELD_X=40, FIELD_Y=40, FIELD_W=1120, FIELD_H=720;
const THIRD_RANGES={defensive:[8,30],middle:[35,65],offensive:[70,92]};
const formations={
'4-3-3':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[43,25,'6'],[43,50,'8'],[43,75,'10'],[70,18,'7'],[73,50,'9'],[70,82,'11']],
'4-5-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[40,12,'7'],[40,32,'6'],[42,50,'8'],[40,68,'10'],[40,88,'11'],[68,50,'9']],
'4-2-3-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[38,38,'6'],[38,62,'8'],[53,18,'7'],[55,50,'10'],[53,82,'11'],[72,50,'9']],
'3-4-3':[[8,50,'1'],[22,25,'3'],[22,50,'4'],[22,75,'5'],[42,12,'2'],[40,38,'6'],[40,62,'8'],[42,88,'7'],[68,18,'10'],[73,50,'9'],[68,82,'11']],
'4-4-2':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[42,15,'7'],[42,38,'6'],[42,62,'8'],[42,85,'11'],[70,38,'9'],[70,62,'10']],
'3-5-2':[[8,50,'1'],[22,25,'3'],[22,50,'4'],[22,75,'5'],[38,10,'2'],[42,30,'6'],[42,50,'8'],[42,70,'10'],[38,90,'7'],[68,38,'9'],[68,62,'11']],
'4-1-4-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[36,50,'6'],[50,15,'7'],[50,38,'8'],[50,62,'10'],[50,85,'11'],[73,50,'9']],
'4-3-1-2':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[42,25,'6'],[42,50,'8'],[42,75,'10'],[58,50,'11'],[72,38,'9'],[72,62,'7']],
'5-3-2':[[8,50,'1'],[18,8,'2'],[22,28,'3'],[22,50,'4'],[22,72,'5'],[18,92,'6'],[42,25,'8'],[42,50,'10'],[42,75,'11'],[68,38,'7'],[68,62,'9']],
'5-4-1':[[8,50,'1'],[18,8,'2'],[22,28,'3'],[22,50,'4'],[22,72,'5'],[18,92,'6'],[42,15,'7'],[42,38,'8'],[42,62,'10'],[42,85,'11'],[72,50,'9']]
};
const D={theme:'dark',title:'',overview:'',notes:'',formation:'4-3-3',phase:'full',viewport:{x:0,y:0,w:100,h:100,mode:'full'},zoneMode:false,zones:[],mode:'select',objects:[],paths:[],slides:[],sel:null,selSlide:null,history:[],future:[],lastFormation:null};
let S=structuredClone(D),oid=1,pid=1,sid=1,drag=null,drawStart=null,playTimer=null,autoTimer=null,animFrame=null,moveOrigins={};
const $=s=>document.querySelector(s),svg=$('#svg'),base=$('#base'),zonesLayer=$('#zones'),high=$('#high'),pathsLayer=$('#paths'),objs=$('#objs'),selLayer=$('#sel');
const U={title:$('#title'),overview:$('#overview'),notes:$('#notes'),formation:$('#formation'),phaseZone:$('#phaseZone'),teamColor:$('#teamColor'),oppColor:$('#oppColor'),objectType:$('#objectType'),lineType:$('#lineType'),selColor:$('#selColor'),selLabel:$('#selLabel'),selSize:$('#selSize'),selRot:$('#selRot'),pathWidth:$('#pathWidth'),pathHead:$('#pathHead'),pathRot:$('#pathRot'),pathBend:$('#pathBend'),library:$('#library'),saveName:$('#saveName'),slides:$('#slides'),modeBadge:$('#modeBadge'),viewBadge:$('#viewBadge'),autoBadge:$('#autoBadge'),drawBtn:$('#drawBtn'),linkMoveBtn:$('#linkMoveBtn'),zoneBtn:$('#zoneBtn')};
function E(t,a={},txt){const e=document.createElementNS(NS,t);for(const[k,v] of Object.entries(a))e.setAttribute(k,v);if(txt!=null)e.textContent=txt;return e}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function hx(h){return /^#[0-9a-f]{6}$/i.test(h)?h:'#5ec4ff'}
function rgba(h,a){h=hx(h).slice(1);const n=parseInt(h,16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function contrast(h){h=hx(h).slice(1);const n=parseInt(h,16),r=n>>16&255,g=n>>8&255,b=n&255;return ((.299*r+.587*g+.114*b)/255)>.68?'#111':'#fff'}
function isPlayer(o){return !!o && ['player-circle','player-triangle','goalkeeper'].includes(o.type)}
function snapshotState(){return JSON.stringify({title:S.title,overview:S.overview,notes:S.notes,formation:S.formation,phase:S.phase,viewport:S.viewport,zoneMode:S.zoneMode,zones:S.zones,mode:S.mode,objects:S.objects,paths:S.paths,slides:S.slides,selSlide:S.selSlide,lastFormation:S.lastFormation})}
function pushH(){S.history.push(snapshotState());if(S.history.length>80)S.history.shift();S.future=[]}
function restore(raw){Object.assign(S,structuredClone(D),JSON.parse(raw));S.sel=null;drawStart=null;stopAnimations(false);sync();refreshIds();render()}
function undo(){if(!S.history.length) return;S.future.push(snapshotState());restore(S.history.pop());save()}
function redo(){if(!S.future.length) return;pushH();restore(S.future.pop());save()}
function save(){localStorage.setItem(KEY,JSON.stringify(S));syncLibrary()}
function load(){const raw=localStorage.getItem(KEY);if(raw) try{S=Object.assign(structuredClone(D),JSON.parse(raw))}catch(e){}sync();refreshIds();save();render()}
function refreshIds(){oid=Math.max(1,...S.objects.map(o=>+String(o.id||'').split('-')[1]||0))+1;pid=Math.max(1,...S.paths.map(p=>+String(p.id||'').split('-')[1]||0))+1;sid=Math.max(1,...S.slides.map(s=>+String(s.id||'').split('-')[1]||0))+1}
function sync(){document.body.classList.toggle('light',S.theme==='light');U.title.value=S.title||'';U.overview.value=S.overview||'';U.notes.value=S.notes||'';U.formation.value=S.formation||'4-3-3';U.phaseZone.value=S.phase||'full';toggleModeButtons()}
function schedule(){U.autoBadge.textContent='Autosave pending…';clearTimeout(autoTimer);autoTimer=setTimeout(()=>{save();U.autoBadge.textContent='Autosave saved';setTimeout(()=>U.autoBadge.textContent='Autosave idle',1200)},900)}
function baseField(){base.innerHTML='<rect x="40" y="40" width="1120" height="720" fill="none" stroke="#fff" stroke-width="6"/><line x1="600" y1="40" x2="600" y2="760" stroke="#fff" stroke-width="4"/><circle cx="600" cy="400" r="90" fill="none" stroke="#fff" stroke-width="4"/><circle cx="600" cy="400" r="4" fill="#fff"/><rect x="40" y="230" width="165" height="340" fill="none" stroke="#fff" stroke-width="4"/><rect x="40" y="300" width="55" height="200" fill="none" stroke="#fff" stroke-width="4"/><rect x="995" y="230" width="165" height="340" fill="none" stroke="#fff" stroke-width="4"/><rect x="1105" y="300" width="55" height="200" fill="none" stroke="#fff" stroke-width="4"/><circle cx="150" cy="400" r="4" fill="#fff"/><circle cx="1050" cy="400" r="4" fill="#fff"/><path d="M205 320 A90 90 0 0 1 205 480" fill="none" stroke="#fff" stroke-width="4"/><path d="M995 320 A90 90 0 0 0 995 480" fill="none" stroke="#fff" stroke-width="4"/>'}
function toViewBox(){const v=S.viewport;return `${v.x/100*1200} ${v.y/100*800} ${v.w/100*1200} ${v.h/100*800}`}
function fieldPx(x,y){return {x:FIELD_X+x/100*FIELD_W,y:FIELD_Y+y/100*FIELD_H}}
function viewToPct(clientX,clientY){const p=svg.createSVGPoint();p.x=clientX;p.y=clientY;const pt=p.matrixTransform(svg.getScreenCTM().inverse());return {x:clamp(((pt.x-FIELD_X)/FIELD_W)*100,0,100),y:clamp(((pt.y-FIELD_Y)/FIELD_H)*100,0,100)}}
function zoneBox(z){const r=Math.floor(z/ZONE_COLS), c=z%ZONE_COLS;return {x:FIELD_X+c*(FIELD_W/ZONE_COLS), y:FIELD_Y+r*(FIELD_H/ZONE_ROWS), w:FIELD_W/ZONE_COLS, h:FIELD_H/ZONE_ROWS}}
function renderZones(){zonesLayer.innerHTML='';zonesLayer.style.pointerEvents=S.zoneMode?'auto':'none';for(let z=0;z<ZONE_COLS*ZONE_ROWS;z++){const b=zoneBox(z);const rect=E('rect',{x:b.x,y:b.y,width:b.w,height:b.h,class:`zone ${S.zoneMode?'sel':''} ${S.zones.includes(z)?'on':''}`});if(S.zoneMode){rect.addEventListener('click',e=>{e.stopPropagation();S.zones=S.zones.includes(z)?S.zones.filter(n=>n!==z):[...S.zones,z];render()});}zonesLayer.append(rect)}}
function setView(mode){if(!S.zones.length)return alert('Select at least one zone first.');const rs=S.zones.map(z=>Math.floor(z/ZONE_COLS)), cs=S.zones.map(z=>z%ZONE_COLS);const r0=Math.min(...rs),r1=Math.max(...rs),c0=Math.min(...cs),c1=Math.max(...cs);S.viewport={x:c0*(100/ZONE_COLS),y:r0*(100/ZONE_ROWS),w:(c1-c0+1)*(100/ZONE_COLS),h:(r1-r0+1)*(100/ZONE_ROWS),mode};S.zoneMode=false;S.mode='select';drawStart=null;render();save()}
function mapFormationX(x, phase, team='home'){if(phase==='full') return team==='home'?x:100-x; const lineup=formations[S.formation].map(p=>p[0]); const min=Math.min(...lineup), max=Math.max(...lineup), span=Math.max(1,max-min); const [start,end]=THIRD_RANGES[phase]; const mapped=start+((x-min)/span)*(end-start); return team==='home'?mapped:100-mapped}
function makeObject(type,x=50,y=50,opt={}){return{id:`obj-${oid++}`,type,x,y,color:opt.color||'#5ec4ff',label:opt.label||'',size:opt.size||(type==='full-goal'?70:type==='ball'?14:type==='highlight'?16:24),rotation:opt.rotation||0,locked:false,z:S.objects.length,meta:opt.meta||{}}}
function addObject(type){pushH();const v=S.viewport;const o=makeObject(type,v.x+v.w/2,v.y+v.h/2);if(type==='text')o.label='Coaching Point';if(type==='cone'||type==='disc')o.size=18;S.objects.push(o);S.sel=o.id;render();save()}
function applyFormation(teams){pushH();S.phase=U.phaseZone.value;S.objects=S.objects.filter(o=>!o.meta.formation);const teamColor=U.teamColor.value, oppColor=U.oppColor.value;formations[S.formation].forEach(p=>S.objects.push(makeObject('player-circle',mapFormationX(p[0],S.phase,'home'),p[1],{color:teamColor,label:p[2],meta:{formation:true,team:'home'}})));if(teams===2){formations[S.formation].forEach(p=>S.objects.push(makeObject('player-triangle',mapFormationX(p[0],S.phase,'away'),100-p[1],{color:oppColor,label:p[2],meta:{formation:true,team:'away'}})))}S.lastFormation={name:S.formation,phase:S.phase,teams};render();save()}
function rotatePoint(px,py,cx,cy,deg){const a=deg*Math.PI/180,dx=px-cx,dy=py-cy;return{x:cx+dx*Math.cos(a)-dy*Math.sin(a),y:cy+dx*Math.sin(a)+dy*Math.cos(a)}}
function buildArrowHead(ex,ey,angle,size,color){const lx=ex-size*Math.cos(angle-Math.PI/7),ly=ey-size*Math.sin(angle-Math.PI/7),rx=ex-size*Math.cos(angle+Math.PI/7),ry=ey-size*Math.sin(angle+Math.PI/7);return E('polygon',{points:`${ex},${ey} ${lx},${ly} ${rx},${ry}`,fill:color,stroke:color,'stroke-width':1})}
function startPercentForPath(p, overrideStart){if(overrideStart) return overrideStart; if(p.objId){const o=S.objects.find(obj=>obj.id===p.objId); if(o) return {x:o.x,y:o.y};} return {x:p.x1,y:p.y1}}
function pathGeometry(p, overrideStart){const startPct=startPercentForPath(p, overrideStart); let a=fieldPx(startPct.x,startPct.y), b=fieldPx(p.x2,p.y2); if(p.rotation){const cx=(a.x+b.x)/2, cy=(a.y+b.y)/2; a=rotatePoint(a.x,a.y,cx,cy,p.rotation); b=rotatePoint(b.x,b.y,cx,cy,p.rotation);} const dx=b.x-a.x, dy=b.y-a.y, len=Math.max(1,Math.hypot(dx,dy)); const nx=-dy/len, ny=dx/len; const bend=p.bend??36; const m={x:(a.x+b.x)/2 + nx*bend, y:(a.y+b.y)/2 + ny*bend}; const angle=p.type==='curved'?Math.atan2(b.y-m.y,b.x-m.x):Math.atan2(dy,dx); const d=p.type==='curved'?`M ${a.x} ${a.y} Q ${m.x} ${m.y} ${b.x} ${b.y}`:`M ${a.x} ${a.y} L ${b.x} ${b.y}`; return {a,b,m,d,angle}}
function pathStroke(p){const color={straight:'#fff',curved:'#fff',dashed:'#fff',pass:'#58dd84',dribble:'#ffd24f',press:'#ff7c7c'}[p.type]||'#fff'; const dash=(p.type==='dashed'||p.type==='pass')?'12 8':(p.type==='dribble'?'4 9':''); return {color,dash}}
function drawPathNode(p, idx){const g=E('g',{class:`path ${p.id===S.sel?'sel':''}`}); const geo=pathGeometry(p); const style=pathStroke(p); const width=p.width||5; const pathEl=E('path',{d:geo.d,fill:'none',stroke:style.color,'stroke-width':width,'stroke-linecap':'round'}); if(style.dash) pathEl.setAttribute('stroke-dasharray',style.dash); g.append(pathEl, buildArrowHead(geo.b.x,geo.b.y,geo.angle,p.head||10,style.color)); g.append(E('text',{x:geo.a.x,y:geo.a.y-16,fill:style.color,'font-size':16,'font-weight':'700','text-anchor':'middle'},p.objId?'M':String(idx+1))); g.addEventListener('pointerdown',e=>{e.stopPropagation();S.sel=p.id;uiSelected();render()}); return g}
function drawObjectNode(o){const g=E('g',{class:`${o.type==='highlight'?'highlight':'obj'} ${o.id===S.sel?'sel':''} ${o.locked?'locked':''}`}); const p=fieldPx(o.x,o.y), s=o.size, c=o.color, t=contrast(c); g.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${o.rotation})`);
 if(o.type==='player-circle'||o.type==='goalkeeper'){const circ=E('circle',{cx:0,cy:0,r:s,fill:c,stroke:'#fff','stroke-width':2}); if(o.type==='goalkeeper') circ.setAttribute('stroke-dasharray','6 4'); g.append(circ,E('text',{x:0,y:5,fill:t,'font-size':Math.max(12,s*.8),'font-weight':'700','text-anchor':'middle','dominant-baseline':'middle'},o.label||''))}
 else if(o.type==='player-triangle'){g.append(E('polygon',{points:`0,${-s} ${s},${s} ${-s},${s}`,fill:c,stroke:'#fff','stroke-width':2}),E('text',{x:0,y:8,fill:t,'font-size':Math.max(11,s*.7),'font-weight':'700','text-anchor':'middle','dominant-baseline':'middle'},o.label||''))}
 else if(o.type==='ball'){g.append(E('circle',{cx:0,cy:0,r:s,fill:'#fff',stroke:'#111','stroke-width':2}),E('polygon',{points:`0,${-s/2} ${s/2},0 0,${s/2} ${-s/2},0`,fill:'#111'}))}
 else if(o.type==='cone'){g.append(E('polygon',{points:`0,${-s} ${s},${s} ${-s},${s}`,fill:c||'#ff9b3d',stroke:'#fff','stroke-width':2}))}
 else if(o.type==='disc'){g.append(E('ellipse',{cx:0,cy:0,rx:s,ry:s/2,fill:c||'#ffd24f',stroke:'#fff','stroke-width':2}))}
 else if(o.type==='pole'){g.append(E('line',{x1:0,y1:-s*1.5,x2:0,y2:s*1.5,stroke:c||'#ffdc63','stroke-width':6}))}
 else if(o.type==='mannequin'){g.append(E('circle',{cx:0,cy:-s*1.1,r:s/3,fill:c||'#d5aa58',stroke:'#fff','stroke-width':1.5}),E('rect',{x:-s/2,y:-s*.6,width:s,height:s*2,fill:'none',stroke:c||'#d5aa58','stroke-width':4,rx:8}))}
 else if(o.type==='mini-goal'){g.append(E('path',{d:`M ${-s*0.95} ${s*0.85} A ${s*1.1} ${s*0.95} 0 0 1 ${-s*0.95} ${-s*0.85}`,fill:'none',stroke:'#fff','stroke-width':4}),E('path',{d:`M ${-s*0.45} ${s*0.42} A ${s*0.55} ${s*0.48} 0 0 1 ${-s*0.45} ${-s*0.42}`,fill:'none',stroke:'#fff','stroke-width':3,opacity:.8}),E('line',{x1:-s*0.95,y1:s*0.85,x2:-s*0.45,y2:s*0.42,stroke:'#fff','stroke-width':3}),E('line',{x1:-s*0.95,y1:-s*0.85,x2:-s*0.45,y2:-s*0.42,stroke:'#fff','stroke-width':3}))}
 else if(o.type==='full-goal'){g.append(E('rect',{x:-s,y:-s/2,width:s*2,height:s,fill:'none',stroke:'#fff','stroke-width':4}),E('line',{x1:-s,y1:s/2,x2:-s*1.25,y2:s*1.1,stroke:'#fff','stroke-width':3}),E('line',{x1:s,y1:s/2,x2:s*1.25,y2:s*1.1,stroke:'#fff','stroke-width':3}))}
 else if(o.type==='text'){g.append(E('text',{x:0,y:0,fill:c,'font-size':s,'font-weight':'700','text-anchor':'start','dominant-baseline':'middle'},o.label||'Text'))}
 else if(o.type==='highlight'){g.append(E('rect',{x:-s*1.8,y:-s,width:s*3.6,height:s*2,fill:rgba(c,.22),stroke:c,'stroke-width':2,rx:8}))}
 g.addEventListener('pointerdown',e=>{e.stopPropagation();S.sel=o.id;uiSelected();if(!o.locked&&S.mode==='select') drag={id:o.id}; render()});
 g.addEventListener('dblclick',e=>{e.stopPropagation();const value=prompt('Label / number',o.label||''); if(value!=null){o.label=value; render(); save()}});
 return g}
function renderObjects(){objs.innerHTML=''; high.innerHTML=''; [...S.objects].sort((a,b)=>a.z-b.z).forEach(o=>(o.type==='highlight'?high:objs).append(drawObjectNode(o)))}
function renderPaths(){pathsLayer.innerHTML=''; S.paths.forEach((p,i)=>pathsLayer.append(drawPathNode(p,i)))}
function renderSelection(){selLayer.innerHTML=''; if(drawStart){const p=fieldPx(drawStart.x,drawStart.y); selLayer.append(E('circle',{cx:p.x,cy:p.y,r:10,fill:'rgba(255,255,255,.15)',stroke:'#fff','stroke-width':3}),E('text',{x:p.x+16,y:p.y-14,fill:'#fff','font-size':14,'font-weight':'700'},'Start'));} const o=S.objects.find(obj=>obj.id===S.sel); if(o){const p=fieldPx(o.x,o.y); selLayer.append(E('rect',{x:p.x-o.size*2.1,y:p.y-o.size*2.1,width:o.size*4.2,height:o.size*4.2,class:'outline'}));}}
function renderSlides(){U.slides.innerHTML=''; S.slides.forEach((s,i)=>{const d=document.createElement('div'); d.className='slide'+(s.id===S.selSlide?' sel':''); d.innerHTML=`<div class="thumb">${s.img?`<img src="${s.img}" alt="slide">`:''}</div><div><strong>${i+1}. ${esc(s.title||'Untitled')}</strong><p>${esc((s.notes||'').slice(0,90)||'No explanation')}</p></div>`; d.onclick=()=>{S.selSlide=s.id;render()}; d.ondblclick=()=>loadSlide(s.id); U.slides.append(d)})}
function toggleModeButtons(){U.drawBtn.classList.toggle('active',S.mode==='draw'); U.linkMoveBtn.classList.toggle('active',S.mode==='link-move'); U.zoneBtn.classList.toggle('active',S.zoneMode)}
function uiSelected(){const o=S.objects.find(x=>x.id===S.sel); const p=S.paths.find(x=>x.id===S.sel); if(o){U.selColor.value=hx(o.color);U.selLabel.value=o.label||'';U.selSize.value=o.size||24;U.selRot.value=o.rotation||0;} if(p){U.pathWidth.value=p.width||5;U.pathHead.value=p.head||10;U.pathRot.value=p.rotation||0;U.pathBend.value=p.bend??36;}}
function render(){svg.setAttribute('viewBox',toViewBox()); U.modeBadge.textContent=S.mode==='draw'?(drawStart?'Mode: draw annotation (click end point)':'Mode: draw annotation (click start point)'):S.mode==='link-move'?'Mode: assign move (click destination for selected player)':(S.zoneMode?'Mode: zone select':'Mode: select'); U.viewBadge.textContent=`View: ${S.viewport.mode}`; toggleModeButtons(); renderZones(); renderPaths(); renderObjects(); renderSelection(); renderSlides(); uiSelected()}
function updateSelectedObject(){const o=S.objects.find(x=>x.id===S.sel); if(!o) return; pushH(); o.color=U.selColor.value; o.label=U.selLabel.value; o.size=+U.selSize.value; o.rotation=+U.selRot.value; render(); save()}
function updateSelectedPath(){const p=S.paths.find(x=>x.id===S.sel); if(!p) return; pushH(); p.width=+U.pathWidth.value; p.head=+U.pathHead.value; p.rotation=+U.pathRot.value; p.bend=+U.pathBend.value; render(); save()}
function reverseSelectedPath(){const p=S.paths.find(x=>x.id===S.sel); if(!p) return; pushH(); if(p.objId){const o=S.objects.find(obj=>obj.id===p.objId); if(o){const tx=p.x2, ty=p.y2; p.x2=o.x; p.y2=o.y; o.x=tx; o.y=ty;}} else {const x1=p.x1,y1=p.y1; p.x1=p.x2; p.y1=p.y2; p.x2=x1; p.y2=y1;} render(); save()}
function duplicateSelected(){const o=S.objects.find(x=>x.id===S.sel); const p=S.paths.find(x=>x.id===S.sel); if(!o && !p) return; pushH(); if(o){const c=JSON.parse(JSON.stringify(o)); c.id=`obj-${oid++}`; c.x=clamp(c.x+3,0,100); c.y=clamp(c.y+3,0,100); c.z=S.objects.length; S.objects.push(c); S.sel=c.id;} else {const c=JSON.parse(JSON.stringify(p)); c.id=`path-${pid++}`; if(!c.objId){c.x1+=2; c.x2+=2;} else {c.objId=null; c.x1+=2; c.x2+=2;} S.paths.push(c); S.sel=c.id;} render(); save()}
function deleteSelected(){if(!S.sel) return; pushH(); S.objects=S.objects.filter(o=>o.id!==S.sel); S.paths=S.paths.filter(p=>p.id!==S.sel && p.objId!==S.sel); S.sel=null; render(); save()}
function moveSelectedZ(dir){const i=S.objects.findIndex(o=>o.id===S.sel); if(i<0) return; const j=clamp(i+dir,0,S.objects.length-1); if(i===j) return; pushH(); const [o]=S.objects.splice(i,1); S.objects.splice(j,0,o); S.objects.forEach((item,idx)=>item.z=idx); render(); save()}
function toggleLockSelected(){const o=S.objects.find(x=>x.id===S.sel); if(!o) return; pushH(); o.locked=!o.locked; render(); save()}
function newSession(){if(!confirm('Start a new session?')) return; S=structuredClone(D); drawStart=null; stopAnimations(false); S.theme=document.body.classList.contains('light')?'light':'dark'; sync(); refreshIds(); render(); save()}
function clearField(){pushH(); S.objects=[]; S.paths=[]; S.sel=null; drawStart=null; stopAnimations(false); render(); save()}
function bezierPoint(a,m,b,t){const u=1-t; return {x:u*u*a.x+2*u*t*m.x+t*t*b.x, y:u*u*a.y+2*u*t*m.y+t*t*b.y}}
function animateLinkedMoves(){const linked=S.paths.filter(p=>p.objId && S.objects.some(o=>o.id===p.objId)); if(!linked.length) return alert('Select a player, click “Assign Move to Selected Player”, then click a destination.'); stopAnimations(false); moveOrigins={}; linked.forEach(p=>{const o=S.objects.find(obj=>obj.id===p.objId); if(o && !(o.id in moveOrigins)) moveOrigins[o.id]={x:o.x,y:o.y};}); const duration=1600; const started=performance.now(); function step(now){const t=Math.min(1,(now-started)/duration); linked.forEach(p=>{const o=S.objects.find(obj=>obj.id===p.objId); if(!o) return; const from=moveOrigins[o.id]||{x:o.x,y:o.y}; const geo=pathGeometry(p, from); let pt; if(p.type==='curved') pt=bezierPoint(geo.a,geo.m,geo.b,t); else pt={x:geo.a.x+(geo.b.x-geo.a.x)*t, y:geo.a.y+(geo.b.y-geo.a.y)*t}; o.x=clamp(((pt.x-FIELD_X)/FIELD_W)*100,0,100); o.y=clamp(((pt.y-FIELD_Y)/FIELD_H)*100,0,100);}); render(); if(t<1) animFrame=requestAnimationFrame(step); else animFrame=null;} animFrame=requestAnimationFrame(step)}
function stopAnimations(reset=true){if(animFrame) cancelAnimationFrame(animFrame); animFrame=null; if(reset && moveOrigins && Object.keys(moveOrigins).length){Object.entries(moveOrigins).forEach(([id,pos])=>{const o=S.objects.find(obj=>obj.id===id); if(o){o.x=pos.x; o.y=pos.y;}}); render();}}
function svgToPng(svgText,w=1200,h=800){return new Promise((resolve,reject)=>{const blob=new Blob([svgText],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image(); img.onload=()=>{const c=document.createElement('canvas'); c.width=w; c.height=h; const x=c.getContext('2d'); x.fillStyle='#0a8e1f'; x.fillRect(0,0,w,h); x.drawImage(img,0,0,w,h); URL.revokeObjectURL(url); resolve(c.toDataURL('image/png'));}; img.onerror=reject; img.src=url;})}
async function snapshot(){const clone=svg.cloneNode(true); clone.setAttribute('xmlns',NS); clone.setAttribute('width',1200); clone.setAttribute('height',800); return svgToPng(new XMLSerializer().serializeToString(clone))}
async function addSlide(update=false){const img=await snapshot(); pushH(); let s=S.slides.find(x=>x.id===S.selSlide); const statePayload={viewport:S.viewport,zones:S.zones,objects:S.objects,paths:S.paths,notes:S.notes,phase:S.phase}; if(update && s){Object.assign(s,{title:S.title||s.title,notes:S.notes,overview:S.overview,img,state:JSON.stringify(statePayload)})} else {s={id:`slide-${sid++}`,title:S.title||`Slide ${S.slides.length+1}`,notes:S.notes,overview:S.overview,img,state:JSON.stringify(statePayload)}; S.slides.push(s); S.selSlide=s.id;} render(); save()}
function loadSlide(id){const s=S.slides.find(x=>x.id===id); if(!s||!s.state) return; pushH(); const d=JSON.parse(s.state); S.viewport=d.viewport; S.zones=d.zones; S.objects=d.objects; S.paths=d.paths; S.phase=d.phase||'full'; S.notes=d.notes||s.notes||''; drawStart=null; stopAnimations(false); U.notes.value=S.notes; U.phaseZone.value=S.phase; S.selSlide=id; refreshIds(); render(); save()}
function moveSlide(dir){const i=S.slides.findIndex(s=>s.id===S.selSlide); if(i<0) return; const j=clamp(i+dir,0,S.slides.length-1); if(i===j) return; pushH(); const [s]=S.slides.splice(i,1); S.slides.splice(j,0,s); render(); save()}
function deleteSlide(){if(!S.selSlide) return; pushH(); S.slides=S.slides.filter(s=>s.id!==S.selSlide); S.selSlide=S.slides[0]?.id||null; render(); save()}
function playSlides(){if(!S.slides.length) return alert('Add slides first.'); stopSlides(); let i=Math.max(0,S.slides.findIndex(s=>s.id===S.selSlide)); loadSlide(S.slides[i].id); playTimer=setInterval(()=>{i=(i+1)%S.slides.length; loadSlide(S.slides[i].id)},2200)}
function stopSlides(){if(playTimer) clearInterval(playTimer); playTimer=null}
function getLibrary(){try{return JSON.parse(localStorage.getItem(LIB))||{}}catch(e){return {}}}
function syncLibrary(selName){const lib=getLibrary(), names=Object.keys(lib).sort((a,b)=>a.localeCompare(b)); U.library.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join(''); if(selName) U.library.value=selName}
function saveSession(){const name=U.saveName.value.trim()||S.title.trim()||`Session ${new Date().toLocaleString()}`; const lib=getLibrary(); lib[name]={savedAt:new Date().toISOString(),state:S}; localStorage.setItem(LIB,JSON.stringify(lib)); syncLibrary(name); save(); alert(`Saved session: ${name}`)}
function loadSession(){const name=U.library.value, lib=getLibrary(); if(!name||!lib[name]) return; if(!confirm(`Load saved session "${name}"?`)) return; S=Object.assign(structuredClone(D),JSON.parse(JSON.stringify(lib[name].state))); drawStart=null; stopAnimations(false); sync(); refreshIds(); render(); save()}
function duplicateSession(){const name=U.library.value, lib=getLibrary(); if(!name||!lib[name]) return; lib[`${name} Copy`]=JSON.parse(JSON.stringify(lib[name])); localStorage.setItem(LIB,JSON.stringify(lib)); syncLibrary(`${name} Copy`)}
function deleteSession(){const name=U.library.value, lib=getLibrary(); if(!name||!lib[name]) return; if(!confirm(`Delete saved session "${name}"?`)) return; delete lib[name]; localStorage.setItem(LIB,JSON.stringify(lib)); syncLibrary()}
function exportJson(){const blob=new Blob([JSON.stringify({app:'Soccer Practice Planner',exportedAt:new Date().toISOString(),state:S},null,2)],{type:'application/json'}), url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url; a.download=(S.title||'soccer-practice-plan').replace(/[^a-z0-9-_]+/gi,'_')+'.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),400)}
function importJson(e){const f=e.target.files?.[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{try{const d=JSON.parse(r.result); S=Object.assign(structuredClone(D),d.state||d); drawStart=null; stopAnimations(false); sync(); refreshIds(); render(); save(); alert('Imported successfully.');}catch(err){alert('Import failed. Invalid JSON.');}}; r.readAsText(f); e.target.value=''}
async function exportPpt(){if(!S.slides.length) return alert('Add slides first.'); if(!window.PptxGenJS) return alert('PptxGenJS failed to load.'); const pptx=new PptxGenJS(); pptx.layout='LAYOUT_WIDE'; pptx.title=S.title||'Soccer Practice Deck'; let sl=pptx.addSlide(); sl.background={color:'0F172A'}; sl.addText(S.title||'Soccer Practice Planner',{x:.4,y:.3,w:12,h:.5,color:'FFFFFF',fontSize:24,bold:true}); sl.addText('Session Overview',{x:.4,y:1,w:3,h:.4,color:'56C7FF',fontSize:16,bold:true}); sl.addText(S.overview||'No overall overview added.',{x:.4,y:1.35,w:12,h:2.4,color:'E8EEF8',fontSize:16,breakLine:true}); for(const it of S.slides){sl=pptx.addSlide(); sl.background={color:'111827'}; sl.addText(it.title||'Practice Slide',{x:.4,y:.25,w:7.5,h:.45,color:'FFFFFF',fontSize:20,bold:true}); sl.addText('Coach Notes',{x:9,y:.25,w:2.5,h:.3,color:'7FF0A7',fontSize:14,bold:true}); sl.addImage({data:it.img,x:.35,y:.85,w:8.2,h:4.6}); sl.addText(it.notes||'No explanation provided.',{x:8.8,y:.75,w:4.1,h:4.8,color:'E8EEF8',fontSize:14,breakLine:true,fill:{color:'1F2937',transparency:15},line:{color:'334155',transparency:10},margin:.1})} await pptx.writeFile({fileName:(S.title||'soccer-practice-deck').replace(/[^a-z0-9-_]+/gi,'_')+'.pptx'})}
function exportPdf(){if(!S.slides.length) return alert('Add slides first.'); const html=`<!doctype html><html><head><title>${esc(S.title||'Soccer Practice Deck')}</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#111}h1,h2,h3{margin:0 0 12px}.slide{page-break-after:always;margin-bottom:28px}.g{display:grid;grid-template-columns:2fr 1fr;gap:20px;align-items:start}img{width:100%;border:1px solid #bbb;border-radius:12px}p{white-space:pre-wrap;line-height:1.45}</style></head><body><h1>${esc(S.title||'Soccer Practice Deck')}</h1><p>${esc(S.overview||'')}</p>${S.slides.map((s,i)=>`<section class="slide"><h2>${esc(s.title||`Slide ${i+1}`)}</h2><div class="g"><img src="${s.img}" alt="slide"><div><h3>Coach Notes</h3><p>${esc(s.notes||'No explanation provided.')}</p></div></div></section>`).join('')}</body></html>`; const w=window.open('','_blank'); w.document.write(html); w.document.close(); w.focus(); setTimeout(()=>w.print(),400)}
function toggleZoneMode(){S.zoneMode=!S.zoneMode; if(S.zoneMode){S.mode='select'; drawStart=null;} render()}
function beginDraw(){S.zoneMode=false; S.mode='draw'; drawStart=null; render()}
function beginLinkMove(){const o=S.objects.find(x=>x.id===S.sel); if(!isPlayer(o)) return alert('Select a player, triangle player, or goalkeeper first.'); S.zoneMode=false; S.mode='link-move'; drawStart=null; render()}
function bind(){Object.keys(formations).forEach(k=>U.formation.insertAdjacentHTML('beforeend',`<option value="${k}">${k}</option>`)); baseField();
 $('#themeBtn').onclick=()=>{S.theme=S.theme==='dark'?'light':'dark'; sync(); save()};
 U.title.oninput=e=>{S.title=e.target.value; schedule()}; U.overview.oninput=e=>{S.overview=e.target.value; schedule()}; U.notes.oninput=e=>{S.notes=e.target.value; schedule()}; U.formation.onchange=e=>{S.formation=e.target.value; save()}; U.phaseZone.onchange=e=>{S.phase=e.target.value; save()};
 $('#oneTeam').onclick=()=>applyFormation(1); $('#twoTeams').onclick=()=>applyFormation(2); $('#addObjectBtn').onclick=()=>addObject(U.objectType.value);
 $('#drawBtn').onclick=beginDraw; $('#linkMoveBtn').onclick=beginLinkMove; $('#cancelDraw').onclick=()=>{S.mode='select'; drawStart=null; render()}; $('#zoneBtn').onclick=toggleZoneMode; $('#zoomBtn').onclick=()=>setView('zoom'); $('#cropBtn').onclick=()=>setView('custom-grid'); $('#fullBtn').onclick=()=>{S.viewport={x:0,y:0,w:100,h:100,mode:'full'}; drawStart=null; S.zoneMode=false; render(); save()};
 $('#animateBtn').onclick=animateLinkedMoves; $('#resetAnimBtn').onclick=()=>stopAnimations(true);
 $('#applySel').onclick=updateSelectedObject; $('#applyPath').onclick=updateSelectedPath; $('#reversePath').onclick=reverseSelectedPath; $('#dupBtn').onclick=duplicateSelected; $('#delBtn').onclick=deleteSelected; $('#frontBtn').onclick=()=>moveSelectedZ(1); $('#backBtn').onclick=()=>moveSelectedZ(-1); $('#lockBtn').onclick=toggleLockSelected;
 $('#undoBtn').onclick=undo; $('#redoBtn').onclick=redo; $('#clearBtn').onclick=clearField; $('#saveBtn').onclick=saveSession; $('#loadBtn').onclick=loadSession; $('#dupSession').onclick=duplicateSession; $('#delSession').onclick=deleteSession; $('#newBtn').onclick=newSession; $('#expJson').onclick=exportJson; $('#impJson').onchange=importJson;
 $('#addSlide').onclick=()=>addSlide(false); $('#updSlide').onclick=()=>addSlide(true); $('#upSlide').onclick=()=>moveSlide(-1); $('#downSlide').onclick=()=>moveSlide(1); $('#delSlide').onclick=deleteSlide; $('#pptBtn').onclick=exportPpt; $('#pdfBtn').onclick=exportPdf; $('#playBtn').onclick=playSlides; $('#stopBtn').onclick=stopSlides;
 svg.addEventListener('click',e=>{if(e.target.closest('.obj,.path,.highlight')) return; const p=viewToPct(e.clientX,e.clientY); if(S.mode==='draw'){if(!drawStart){drawStart=p; render()} else {pushH(); S.paths.push({id:`path-${pid++}`, type:U.lineType.value, x1:drawStart.x, y1:drawStart.y, x2:p.x, y2:p.y, width:+U.pathWidth.value, head:+U.pathHead.value, rotation:+U.pathRot.value, bend:+U.pathBend.value, objId:null}); drawStart=null; S.mode='select'; render(); save()} return;} if(S.mode==='link-move'){const o=S.objects.find(x=>x.id===S.sel); if(!isPlayer(o)) return; pushH(); S.paths.push({id:`path-${pid++}`, type:U.lineType.value, x1:o.x, y1:o.y, x2:p.x, y2:p.y, width:+U.pathWidth.value, head:+U.pathHead.value, rotation:+U.pathRot.value, bend:+U.pathBend.value, objId:o.id}); S.mode='select'; render(); save(); return;} if(S.zoneMode) return; S.sel=null; render();});
 window.addEventListener('pointermove',e=>{if(!drag) return; const o=S.objects.find(x=>x.id===drag.id); if(!o||o.locked) return; const p=viewToPct(e.clientX,e.clientY); o.x=p.x; o.y=p.y; render()});
 window.addEventListener('pointerup',()=>{if(drag){pushH(); drag=null; save()}});
 window.addEventListener('keydown',e=>{const m=e.ctrlKey||e.metaKey; if(m&&e.key.toLowerCase()==='z'){e.preventDefault(); undo()} if(m&&e.key.toLowerCase()==='y'){e.preventDefault(); redo()} if(m&&e.key.toLowerCase()==='d'){e.preventDefault(); duplicateSelected()} if(m&&e.key.toLowerCase()==='s'){e.preventDefault(); saveSession()} if(e.key==='Delete'||e.key==='Backspace') deleteSelected()}); }
bind(); load();
