const NS='http://www.w3.org/2000/svg',KEY='soccerPlannerV2',LIB='soccerPlannerLibraryV2';
const forms={
'4-3-3':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[43,25,'6'],[43,50,'8'],[43,75,'10'],[70,18,'7'],[73,50,'9'],[70,82,'11']],
'4-5-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[40,12,'7'],[40,32,'6'],[42,50,'8'],[40,68,'10'],[40,88,'11'],[68,50,'9']],
'4-2-3-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[38,38,'6'],[38,62,'8'],[53,18,'7'],[55,50,'10'],[53,82,'11'],[72,50,'9']],
'3-4-3':[[8,50,'1'],[22,25,'3'],[22,50,'4'],[22,75,'5'],[42,12,'2'],[40,38,'6'],[40,62,'8'],[42,88,'7'],[68,18,'10'],[73,50,'9'],[68,82,'11']],
'4-4-2':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[42,15,'7'],[42,38,'6'],[42,62,'8'],[42,85,'11'],[70,38,'9'],[70,62,'10']],
'3-5-2':[[8,50,'1'],[22,25,'3'],[22,50,'4'],[22,75,'5'],[38,10,'2'],[42,30,'6'],[42,50,'8'],[42,70,'10'],[38,90,'7'],[68,38,'9'],[68,62,'11']],
'4-1-4-1':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[36,50,'6'],[50,15,'7'],[50,38,'8'],[50,62,'10'],[50,85,'11'],[73,50,'9']],
'4-3-1-2':[[8,50,'1'],[22,15,'2'],[22,38,'3'],[22,62,'4'],[22,85,'5'],[42,25,'6'],[42,50,'8'],[42,75,'10'],[58,50,'11'],[72,38,'9'],[72,62,'7']],
'5-3-2':[[8,50,'1'],[18,8,'2'],[22,28,'3'],[22,50,'4'],[22,72,'5'],[18,92,'6'],[42,25,'8'],[42,50,'10'],[42,75,'11'],[68,38,'7'],[68,62,'9']],
'5-4-1':[[8,50,'1'],[18,8,'2'],[22,28,'3'],[22,50,'4'],[22,72,'5'],[18,92,'6'],[42,15,'7'],[42,38,'8'],[42,62,'10'],[42,85,'11'],[72,50,'9']]
};
const D={theme:'dark',title:'',overview:'',notes:'',formation:'4-3-3',viewport:{x:0,y:0,w:100,h:100,mode:'full'},zoneMode:false,zones:[],mode:'select',objects:[],paths:[],slides:[],sel:null,selSlide:null,history:[],future:[],lastFormation:null};
let S=structuredClone(D),oid=1,pid=1,sid=1,drag=null,drawStart=null,playTimer=null,autoTimer=null;
const $=s=>document.querySelector(s),svg=$('#svg'),base=$('#base'),zones=$('#zones'),high=$('#high'),paths=$('#paths'),objs=$('#objs'),sel=$('#sel');
const U={title:$('#title'),overview:$('#overview'),notes:$('#notes'),formation:$('#formation'),teamColor:$('#teamColor'),oppColor:$('#oppColor'),lineType:$('#lineType'),selColor:$('#selColor'),selLabel:$('#selLabel'),selSize:$('#selSize'),selRot:$('#selRot'),library:$('#library'),saveName:$('#saveName'),slides:$('#slides'),modeBadge:$('#modeBadge'),viewBadge:$('#viewBadge'),autoBadge:$('#autoBadge')};
function E(t,a={},txt){const e=document.createElementNS(NS,t);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);if(txt!=null)e.textContent=txt;return e}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function hx(h){return /^#[0-9a-f]{6}$/i.test(h)?h:'#5ec4ff'}
function rgba(h,a){h=hx(h).slice(1);const n=parseInt(h,16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function contrast(h){h=hx(h).slice(1);const n=parseInt(h,16),r=n>>16&255,g=n>>8&255,b=n&255;return((.299*r+.587*g+.114*b)/255)>.68?'#111':'#fff'}
function pushH(){S.history.push(JSON.stringify({title:S.title,overview:S.overview,notes:S.notes,formation:S.formation,viewport:S.viewport,zoneMode:S.zoneMode,zones:S.zones,mode:S.mode,objects:S.objects,paths:S.paths,slides:S.slides,selSlide:S.selSlide,lastFormation:S.lastFormation}));if(S.history.length>60)S.history.shift();S.future=[]}
function restore(raw){Object.assign(S,structuredClone(D),JSON.parse(raw));S.sel=null;sync();refreshIds();render()}
function undo(){if(!S.history.length)return;S.future.push(JSON.stringify({title:S.title,overview:S.overview,notes:S.notes,formation:S.formation,viewport:S.viewport,zoneMode:S.zoneMode,zones:S.zones,mode:S.mode,objects:S.objects,paths:S.paths,slides:S.slides,selSlide:S.selSlide,lastFormation:S.lastFormation}));restore(S.history.pop());save()}
function redo(){if(!S.future.length)return;pushH();restore(S.future.pop());save()}
function save(){localStorage.setItem(KEY,JSON.stringify(S));syncLib()}
function load(){const raw=localStorage.getItem(KEY);if(raw)try{S=Object.assign(structuredClone(D),JSON.parse(raw))}catch(e){}sync();refreshIds();save();render()}
function sync(){document.body.classList.toggle('light',S.theme==='light');U.title.value=S.title||'';U.overview.value=S.overview||'';U.notes.value=S.notes||'';U.formation.value=S.formation||'4-3-3'}
function refreshIds(){oid=Math.max(1,...S.objects.map(o=>+o.id.split('-')[1]||0))+1;pid=Math.max(1,...S.paths.map(o=>+o.id.split('-')[1]||0))+1;sid=Math.max(1,...S.slides.map(o=>+o.id.split('-')[1]||0))+1}
function schedule(){U.autoBadge.textContent='Autosave pending…';clearTimeout(autoTimer);autoTimer=setTimeout(()=>{save();U.autoBadge.textContent='Autosave saved';setTimeout(()=>U.autoBadge.textContent='Autosave idle',1200)},900)}
function baseField(){base.innerHTML='<rect x="40" y="40" width="1120" height="720" fill="none" stroke="#fff" stroke-width="6"/><line x1="600" y1="40" x2="600" y2="760" stroke="#fff" stroke-width="4"/><circle cx="600" cy="400" r="90" fill="none" stroke="#fff" stroke-width="4"/><circle cx="600" cy="400" r="4" fill="#fff"/><rect x="40" y="230" width="165" height="340" fill="none" stroke="#fff" stroke-width="4"/><rect x="40" y="300" width="55" height="200" fill="none" stroke="#fff" stroke-width="4"/><rect x="995" y="230" width="165" height="340" fill="none" stroke="#fff" stroke-width="4"/><rect x="1105" y="300" width="55" height="200" fill="none" stroke="#fff" stroke-width="4"/><circle cx="150" cy="400" r="4" fill="#fff"/><circle cx="1050" cy="400" r="4" fill="#fff"/><path d="M205 320 A90 90 0 0 1 205 480" fill="none" stroke="#fff" stroke-width="4"/><path d="M995 320 A90 90 0 0 0 995 480" fill="none" stroke="#fff" stroke-width="4"/>'}
function toViewBox(){const v=S.viewport;return `${v.x/100*1200} ${v.y/100*800} ${v.w/100*1200} ${v.h/100*800}`}
function fieldPx(x,y){return{x:40+x/100*1120,y:40+y/100*720}}
function viewToPct(clientX,clientY){const p=svg.createSVGPoint();p.x=clientX;p.y=clientY;const pt=p.matrixTransform(svg.getScreenCTM().inverse());const [vx,vy,vw,vh]=svg.getAttribute('viewBox').split(/\s+/).map(Number);const fx=S.viewport.x+((pt.x-vx)/(vw))*S.viewport.w,fy=S.viewport.y+((pt.y-vy)/(vh))*S.viewport.h;return{x:clamp(fx,0,100),y:clamp(fy,0,100)}}
function obj(type,x=50,y=50,opt={}){return{id:`obj-${oid++}`,type,x,y,color:opt.color||'#5ec4ff',label:opt.label||'',size:opt.size||(type==='full-goal'?70:type==='ball'?14:type==='highlight'?16:24),rotation:opt.rotation||0,locked:false,z:S.objects.length,meta:opt.meta||{}}}
function add(type){pushH();const v=S.viewport,o=obj(type,v.x+v.w/2,v.y+v.h/2);if(type==='text')o.label='Coaching Point';if(type==='cone'||type==='disc')o.size=18;S.objects.push(o);S.sel=o.id;render();save()}
function applyForm(teams){pushH();S.objects=S.objects.filter(o=>!o.meta.formation);const home=U.teamColor.value,away=U.oppColor.value;forms[S.formation].forEach(p=>S.objects.push(obj('player-circle',p[0],p[1],{color:home,label:p[2],meta:{formation:1,team:'home'}})));if(teams===2)forms[S.formation].forEach(p=>S.objects.push(obj('player-triangle',100-p[0],100-p[1],{color:away,label:p[2],meta:{formation:1,team:'away'}})));S.lastFormation={name:S.formation,teams};render();save()}
function zoneBox(z){const r=Math.floor(z/5),c=z%5;return{x:40+c*224,y:40+r*240,w:224,h:240}}
function renderZones(){zones.innerHTML='';for(let z=0;z<15;z++){const b=zoneBox(z),r=E('rect',{x:b.x,y:b.y,width:b.w,height:b.h,class:`zone ${S.zoneMode?'sel':''} ${S.zones.includes(z)?'on':''}`});r.addEventListener('click',e=>{if(!S.zoneMode)return;e.stopPropagation();S.zones=S.zones.includes(z)?S.zones.filter(n=>n!==z):[...S.zones,z];render()});zones.append(r)}}
function setView(mode){if(!S.zones.length)return alert('Select at least one zone first.');const rs=S.zones.map(z=>Math.floor(z/5)),cs=S.zones.map(z=>z%5),r0=Math.min(...rs),r1=Math.max(...rs),c0=Math.min(...cs),c1=Math.max(...cs);S.viewport={x:c0*20,y:r0*(100/3),w:(c1-c0+1)*20,h:(r1-r0+1)*(100/3),mode};S.zoneMode=false;S.mode='select';render();save()}
function drawShape(o){const g=E('g',{class:`${o.type==='highlight'?'highlight':'obj'} ${o.id===S.sel?'sel':''} ${o.locked?'locked':''}`});const p=fieldPx(o.x,o.y),s=o.size,c=o.color,t=contrast(c);g.dataset.id=o.id;g.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${o.rotation})`);let a;
if(o.type==='player-circle'||o.type==='goalkeeper'){a=E('circle',{cx:0,cy:0,r:s,fill:c,stroke:'#fff','stroke-width':2});if(o.type==='goalkeeper')a.setAttribute('stroke-dasharray','6 4');g.append(a,E('text',{x:0,y:5,fill:t,'font-size':Math.max(12,s*.8),'font-weight':'700','text-anchor':'middle','dominant-baseline':'middle'},o.label||''))}
else if(o.type==='player-triangle'){a=E('polygon',{points:`0,${-s} ${s},${s} ${-s},${s}`,fill:c,stroke:'#fff','stroke-width':2});g.append(a,E('text',{x:0,y:8,fill:t,'font-size':Math.max(11,s*.7),'font-weight':'700','text-anchor':'middle','dominant-baseline':'middle'},o.label||''))}
else if(o.type==='ball'){g.append(E('circle',{cx:0,cy:0,r:s,fill:'#fff',stroke:'#111','stroke-width':2}),E('polygon',{points:`0,${-s/2} ${s/2},0 0,${s/2} ${-s/2},0`,fill:'#111'}))}
else if(o.type==='cone'){g.append(E('polygon',{points:`0,${-s} ${s},${s} ${-s},${s}`,fill:c||'#ff9b3d',stroke:'#fff','stroke-width':2}))}
else if(o.type==='disc'){g.append(E('ellipse',{cx:0,cy:0,rx:s,ry:s/2,fill:c||'#ffd24f',stroke:'#fff','stroke-width':2}))}
else if(o.type==='pole'){g.append(E('line',{x1:0,y1:-s*1.5,x2:0,y2:s*1.5,stroke:c||'#ffdc63','stroke-width':6}))}
else if(o.type==='mannequin'){g.append(E('circle',{cx:0,cy:-s*1.1,r:s/3,fill:c||'#d5aa58',stroke:'#fff','stroke-width':1.5}),E('rect',{x:-s/2,y:-s*.6,width:s,height:s*2,fill:'none',stroke:c||'#d5aa58','stroke-width':4,rx:8}))}
else if(o.type==='mini-goal'){g.append(E('path',{d:`M${-s} ${s} L${-s} ${-s} L${s} ${-s}`,fill:'none',stroke:'#fff','stroke-width':4}))}
else if(o.type==='full-goal'){g.append(E('rect',{x:-s,y:-s/2,width:s*2,height:s,fill:'none',stroke:'#fff','stroke-width':4}),E('line',{x1:-s,y1:s/2,x2:-s*1.25,y2:s*1.1,stroke:'#fff','stroke-width':3}),E('line',{x1:s,y1:s/2,x2:s*1.25,y2:s*1.1,stroke:'#fff','stroke-width':3}))}
else if(o.type==='text'){g.append(E('text',{x:0,y:0,fill:c,'font-size':s,'font-weight':'700','text-anchor':'start','dominant-baseline':'middle'},o.label||'Text'))}
else if(o.type==='highlight'){g.append(E('rect',{x:-s*1.8,y:-s,width:s*3.6,height:s*2,fill:rgba(c,.22),stroke:c,'stroke-width':2,rx:8}))}
 g.addEventListener('pointerdown',e=>{e.stopPropagation();S.sel=o.id;uiSelected();if(!o.locked&&S.mode==='select')drag={id:o.id,p:e.pointerId};render()});g.addEventListener('dblclick',e=>{e.stopPropagation();const v=prompt('Label / number',o.label||'');if(v!=null){o.label=v;render();save()}});return g}
function renderObjs(){objs.innerHTML='';high.innerHTML='';[...S.objects].sort((a,b)=>a.z-b.z).forEach(o=>(o.type==='highlight'?high:objs).append(drawShape(o)))}
function renderPaths(){paths.innerHTML='';S.paths.forEach((p,i)=>{const g=E('g',{class:`path ${p.id===S.sel?'sel':''}`}),a=fieldPx(p.x1,p.y1),b=fieldPx(p.x2,p.y2),col={straight:'#fff',curved:'#fff',dashed:'#fff',pass:'#58dd84',dribble:'#ffd24f',press:'#ff7c7c'}[p.type]||'#fff';let shp;if(p.type==='curved'){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2-Math.max(30,Math.abs(b.x-a.x)*.12);shp=E('path',{d:`M ${a.x} ${a.y} Q ${mx} ${my} ${b.x} ${b.y}`,fill:'none',stroke:col,'stroke-width':5,'marker-end':'url(#arrowHead)'})}else{shp=E('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:col,'stroke-width':5,'marker-end':'url(#arrowHead)'});if(p.type==='dashed'||p.type==='pass')shp.setAttribute('stroke-dasharray','12 8');if(p.type==='dribble')shp.setAttribute('stroke-dasharray','4 9')}g.append(shp,E('text',{x:a.x,y:a.y-16,fill:col,'font-size':16,'font-weight':'700','text-anchor':'middle'},String(i+1)));g.addEventListener('pointerdown',e=>{e.stopPropagation();S.sel=p.id;render()});paths.append(g)})}
function renderSelection(){sel.innerHTML='';const o=S.objects.find(x=>x.id===S.sel);if(!o)return;const p=fieldPx(o.x,o.y);sel.append(E('rect',{x:p.x-o.size*2.1,y:p.y-o.size*2.1,width:o.size*4.2,height:o.size*4.2,class:'outline'}))}
function renderSlides(){U.slides.innerHTML='';S.slides.forEach((s,i)=>{const d=document.createElement('div');d.className='slide'+(s.id===S.selSlide?' sel':'');d.innerHTML=`<div class="thumb">${s.img?`<img src="${s.img}" alt="slide">`:''}</div><div><strong>${i+1}. ${esc(s.title||'Untitled')}</strong><p>${esc((s.notes||'').slice(0,90)||'No explanation')}</p></div>`;d.onclick=()=>{S.selSlide=s.id;render()};d.ondblclick=()=>loadSlide(s.id);U.slides.append(d)})}
function uiSelected(){const o=S.objects.find(x=>x.id===S.sel);if(!o)return;U.selColor.value=hx(o.color);U.selLabel.value=o.label||'';U.selSize.value=o.size||24;U.selRot.value=o.rotation||0}
function render(){svg.setAttribute('viewBox',toViewBox());U.modeBadge.textContent=`Mode: ${S.mode}`;U.viewBadge.textContent=`View: ${S.viewport.mode}`;renderZones();renderPaths();renderObjs();renderSelection();renderSlides();uiSelected()}
function pick(){return S.objects.find(x=>x.id===S.sel)||S.paths.find(x=>x.id===S.sel)}
function updateSel(){const o=S.objects.find(x=>x.id===S.sel);if(!o)return;pushH();o.color=U.selColor.value;o.label=U.selLabel.value;o.size=+U.selSize.value;o.rotation=+U.selRot.value;render();save()}
function dupSel(){const it=pick();if(!it)return;pushH();if(it.id.startsWith('obj-')){const c=JSON.parse(JSON.stringify(it));c.id=`obj-${oid++}`;c.x=clamp(c.x+3,0,100);c.y=clamp(c.y+3,0,100);c.z=S.objects.length;S.objects.push(c);S.sel=c.id}else{const c=JSON.parse(JSON.stringify(it));c.id=`path-${pid++}`;c.x1+=2;c.x2+=2;S.paths.push(c);S.sel=c.id}render();save()}
function delSel(){if(!S.sel)return;pushH();S.objects=S.objects.filter(o=>o.id!==S.sel);S.paths=S.paths.filter(o=>o.id!==S.sel);S.sel=null;render();save()}
function moveZ(dir){const i=S.objects.findIndex(o=>o.id===S.sel);if(i<0)return;const j=clamp(i+dir,0,S.objects.length-1);if(i===j)return;pushH();const[o]=S.objects.splice(i,1);S.objects.splice(j,0,o);S.objects.forEach((o,i)=>o.z=i);render();save()}
function lockSel(){const o=S.objects.find(x=>x.id===S.sel);if(!o)return;pushH();o.locked=!o.locked;render();save()}
function reset(){if(!confirm('Start a new session?'))return;S=structuredClone(D);S.theme=document.body.classList.contains('light')?'light':'dark';sync();refreshIds();render();save()}
function clearField(){pushH();S.objects=[];S.paths=[];S.sel=null;render();save()}
function svgPng(svgText,w=1200,h=800){return new Promise((res,rej)=>{const blob=new Blob([svgText],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#0a8e1f';x.fillRect(0,0,w,h);x.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);res(c.toDataURL('image/png'))};img.onerror=rej;img.src=url})}
async function snapshot(){const clone=svg.cloneNode(true);clone.setAttribute('xmlns',NS);clone.setAttribute('width',1200);clone.setAttribute('height',800);return svgPng(new XMLSerializer().serializeToString(clone))}
async function addSlide(update=false){const img=await snapshot();pushH();let s=S.slides.find(x=>x.id===S.selSlide);if(update&&s){Object.assign(s,{title:S.title||s.title,notes:S.notes,overview:S.overview,img,state:JSON.stringify({viewport:S.viewport,zones:S.zones,objects:S.objects,paths:S.paths,notes:S.notes})})}else{s={id:`slide-${sid++}`,title:S.title||`Slide ${S.slides.length+1}`,notes:S.notes,overview:S.overview,img,state:JSON.stringify({viewport:S.viewport,zones:S.zones,objects:S.objects,paths:S.paths,notes:S.notes})};S.slides.push(s);S.selSlide=s.id}render();save()}
function loadSlide(id){const s=S.slides.find(x=>x.id===id);if(!s||!s.state)return;pushH();const d=JSON.parse(s.state);S.viewport=d.viewport;S.zones=d.zones;S.objects=d.objects;S.paths=d.paths;S.notes=d.notes||s.notes||'';U.notes.value=S.notes;S.selSlide=id;refreshIds();render();save()}
function moveSlide(dir){const i=S.slides.findIndex(s=>s.id===S.selSlide);if(i<0)return;const j=clamp(i+dir,0,S.slides.length-1);if(i===j)return;pushH();const[s]=S.slides.splice(i,1);S.slides.splice(j,0,s);render();save()}
function delSlide(){if(!S.selSlide)return;pushH();S.slides=S.slides.filter(s=>s.id!==S.selSlide);S.selSlide=S.slides[0]?.id||null;render();save()}
function play(){if(!S.slides.length)return alert('Add slides first.');stop();let i=Math.max(0,S.slides.findIndex(s=>s.id===S.selSlide));loadSlide(S.slides[i].id);playTimer=setInterval(()=>{i=(i+1)%S.slides.length;loadSlide(S.slides[i].id)},2200)}
function stop(){if(playTimer)clearInterval(playTimer);playTimer=null}
function lib(){try{return JSON.parse(localStorage.getItem(LIB))||{}}catch(e){return{}}}
function syncLib(selName){const l=lib(),names=Object.keys(l).sort((a,b)=>a.localeCompare(b));U.library.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(selName)U.library.value=selName}
function saveLib(){const name=U.saveName.value.trim()||S.title.trim()||`Session ${new Date().toLocaleString()}`;const l=lib();l[name]={savedAt:new Date().toISOString(),state:S};localStorage.setItem(LIB,JSON.stringify(l));syncLib(name);save();alert(`Saved session: ${name}`)}
function loadLib(){const n=U.library.value,l=lib();if(!n||!l[n])return;if(!confirm(`Load saved session "${n}"?`))return;S=Object.assign(structuredClone(D),JSON.parse(JSON.stringify(l[n].state)));sync();refreshIds();render();save()}
function dupLib(){const n=U.library.value,l=lib();if(!n||!l[n])return;l[`${n} Copy`]=JSON.parse(JSON.stringify(l[n]));localStorage.setItem(LIB,JSON.stringify(l));syncLib(`${n} Copy`)}
function delLib(){const n=U.library.value,l=lib();if(!n||!l[n])return;if(!confirm(`Delete saved session "${n}"?`))return;delete l[n];localStorage.setItem(LIB,JSON.stringify(l));syncLib()}
function expJson(){const blob=new Blob([JSON.stringify({app:'Soccer Practice Planner',exportedAt:new Date().toISOString(),state:S},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(S.title||'soccer-practice-plan').replace(/[^a-z0-9-_]+/gi,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),400)}
function impJson(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);S=Object.assign(structuredClone(D),d.state||d);sync();refreshIds();render();save();alert('Imported successfully.')}catch(err){alert('Import failed. Invalid JSON.')}};r.readAsText(f);e.target.value=''}
async function ppt(){if(!S.slides.length)return alert('Add slides first.');if(!window.PptxGenJS)return alert('PptxGenJS failed to load.');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.title=S.title||'Soccer Practice Deck';let sl=pptx.addSlide();sl.background={color:'0F172A'};sl.addText(S.title||'Soccer Practice Planner',{x:.4,y:.3,w:12,h:.5,color:'FFFFFF',fontSize:24,bold:true});sl.addText('Session Overview',{x:.4,y:1,w:3,h:.4,color:'56C7FF',fontSize:16,bold:true});sl.addText(S.overview||'No overall overview added.',{x:.4,y:1.35,w:12,h:2.4,color:'E8EEF8',fontSize:16,breakLine:true});for(const it of S.slides){sl=pptx.addSlide();sl.background={color:'111827'};sl.addText(it.title||'Practice Slide',{x:.4,y:.25,w:7.5,h:.45,color:'FFFFFF',fontSize:20,bold:true});sl.addText('Coach Notes',{x:9,y:.25,w:2.5,h:.3,color:'7FF0A7',fontSize:14,bold:true});sl.addImage({data:it.img,x:.35,y:.85,w:8.2,h:4.6});sl.addText(it.notes||'No explanation provided.',{x:8.8,y:.75,w:4.1,h:4.8,color:'E8EEF8',fontSize:14,breakLine:true,fill:{color:'1F2937',transparency:15},line:{color:'334155',transparency:10},margin:.1})}await pptx.writeFile({fileName:(S.title||'soccer-practice-deck').replace(/[^a-z0-9-_]+/gi,'_')+'.pptx'})}
function pdf(){if(!S.slides.length)return alert('Add slides first.');const html=`<!doctype html><html><head><title>${esc(S.title||'Soccer Practice Deck')}</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#111}h1,h2,h3{margin:0 0 12px}.slide{page-break-after:always;margin-bottom:28px}.g{display:grid;grid-template-columns:2fr 1fr;gap:20px;align-items:start}img{width:100%;border:1px solid #bbb;border-radius:12px}p{white-space:pre-wrap;line-height:1.45}</style></head><body><h1>${esc(S.title||'Soccer Practice Deck')}</h1><p>${esc(S.overview||'')}</p>${S.slides.map((s,i)=>`<section class="slide"><h2>${esc(s.title||`Slide ${i+1}`)}</h2><div class="g"><img src="${s.img}" alt="slide"><div><h3>Coach Notes</h3><p>${esc(s.notes||'No explanation provided.')}</p></div></div></section>`).join('')}</body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),400)}
function bind(){Object.keys(forms).forEach(k=>U.formation.insertAdjacentHTML('beforeend',`<option value="${k}">${k}</option>`));baseField();
$('#themeBtn').onclick=()=>{S.theme=S.theme==='dark'?'light':'dark';sync();save()};U.title.oninput=e=>{S.title=e.target.value;schedule()};U.overview.oninput=e=>{S.overview=e.target.value;schedule()};U.notes.oninput=e=>{S.notes=e.target.value;schedule()};U.formation.onchange=e=>{S.formation=e.target.value;save()};
$('#oneTeam').onclick=()=>applyForm(1);$('#twoTeams').onclick=()=>applyForm(2);document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));
$('#drawBtn').onclick=()=>{S.mode='draw';drawStart=null;render()};$('#cancelDraw').onclick=()=>{S.mode='select';drawStart=null;render()};$('#zoneBtn').onclick=()=>{S.zoneMode=!S.zoneMode;S.mode=S.zoneMode?'zone-select':'select';render()};$('#zoomBtn').onclick=()=>setView('zoom');$('#cropBtn').onclick=()=>setView('custom-grid');$('#fullBtn').onclick=()=>{S.viewport={x:0,y:0,w:100,h:100,mode:'full'};render();save()};
$('#applySel').onclick=updateSel;$('#dupBtn').onclick=dupSel;$('#delBtn').onclick=delSel;$('#frontBtn').onclick=()=>moveZ(1);$('#backBtn').onclick=()=>moveZ(-1);$('#lockBtn').onclick=lockSel;
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#clearBtn').onclick=clearField;$('#saveBtn').onclick=saveLib;$('#loadBtn').onclick=loadLib;$('#dupSession').onclick=dupLib;$('#delSession').onclick=delLib;$('#newBtn').onclick=reset;$('#expJson').onclick=expJson;$('#impJson').onchange=impJson;
$('#addSlide').onclick=()=>addSlide(false);$('#updSlide').onclick=()=>addSlide(true);$('#upSlide').onclick=()=>moveSlide(-1);$('#downSlide').onclick=()=>moveSlide(1);$('#delSlide').onclick=delSlide;$('#pptBtn').onclick=ppt;$('#pdfBtn').onclick=pdf;$('#playBtn').onclick=play;$('#stopBtn').onclick=stop;
svg.addEventListener('pointerdown',e=>{if(e.target.closest('.obj,.path,.highlight'))return;if(S.mode==='draw'){const p=viewToPct(e.clientX,e.clientY);if(!drawStart){drawStart=p;U.modeBadge.textContent='Mode: draw (choose end point)'}else{pushH();S.paths.push({id:`path-${pid++}`,type:U.lineType.value,x1:drawStart.x,y1:drawStart.y,x2:p.x,y2:p.y});drawStart=null;S.mode='select';render();save()}return}if(S.zoneMode)return;S.sel=null;render()});
window.addEventListener('pointermove',e=>{if(!drag)return;const o=S.objects.find(x=>x.id===drag.id);if(!o||o.locked)return;const p=viewToPct(e.clientX,e.clientY);o.x=p.x;o.y=p.y;render()});
window.addEventListener('pointerup',()=>{if(drag){pushH();drag=null;save()}});
window.addEventListener('keydown',e=>{const m=e.ctrlKey||e.metaKey;if(m&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if(m&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if(m&&e.key.toLowerCase()==='d'){e.preventDefault();dupSel()}if(m&&e.key.toLowerCase()==='s'){e.preventDefault();saveLib()}if(e.key==='Delete'||e.key==='Backspace')delSel()})}
bind();load();